services:
  frontend:
    develop:
      watch:
        - action: rebuild
          path: ./../frontend/package.json
          target: /app/package.json
        - action: rebuild
          path: ./../frontend/.configs/
          target: /app/.configs/
        - action: rebuild
          path: ./../frontend/src/
          target: /app/src/
