services:
  frontend:
    build:
      target: dev
    container_name: frontend-dev
    env_file:
      - ./.dev.env
    environment:
      NODE_ENV: development
    ports:
      - ${FRONTEND_HOST_PORT:-8080}:${VITE_PORT:-8080}
