services:
  base:
    build:
      args:
        DOMAIN: ${DOMAIN:-localhost}
      context: ./../
      dockerfile: ./.docker/Dockerfile
    ports:
      - ${FRONTEND_HOST_PORT:-8080}:${VITE_PORT:-8080}
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      VITE_HOST: ${VITE_HOST:-0.0.0.0}
      VITE_PORT: ${VITE_PORT:-8080}
