services:
  frontend:
    develop:
      watch:
        # for stack container (docker compose up from project's root directory)
        - action: rebuild
          path: ./../frontend/package.json
          target: /app/package.json
        - action: rebuild
          path: ./../frontend/.configs/
          target: /app/.configs/
        - action: sync
          path: ./../frontend/src/
          target: /app/src/

        # for only frontend container (docker compose up from frontend's root directory)
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: rebuild
          path: ./.configs/
          target: /app/.configs/
        - action: sync
          path: ./src/
          target: /app/src/
